version: '3.0'
services:
  db:
    image: mysql
    container_name: redmine-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redmine
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: redmine-phpmyadmin
    depends_on: 
      - db
    ports:
      - 2001:80
    restart: always
  redmine: 
    build: .
    image: docker.io/jhaoheng/redmine-max:v2.0
    container_name: redmine-main
    ports:
      - 2000:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: root
      REDMINE_PLUGINS_MIGRATE: 1
    depends_on:
      - db
    restart: always 