version: '3.0'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: redmine-phpmyadmin
    depends_on: 
      - db
    ports:
      - 8001:80
    restart: always

  db:
    image: mariadb:10.2.12
    container_name: redmine-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redmine
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redmine:
    image: redmine:3.3.6
    container_name: redmine
    ports:
      - 8000:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: root
      REDMINE_PLUGINS_MIGRATE: 1
    depends_on:
      - db
    volumes:
      - ./theme/abacus_office_blues_1.2.6:/usr/src/redmine/public/themes/abacus_office_blues_1.2.6
      - ./config/configuration.yml:/usr/src/redmine/config/configuration.yml
      - ./plugins/plugins.sh:/usr/src/plugins/plugins.sh
    restart: always

  nginx:
    image: nginx:1.15.0 
    container_name: nginx
    depends_on: 
      - redmine
    ports:
      - 443:443/tcp
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    tty: true
